import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";

export default defineConfig([
  ...nextVitals,
  globalIgnores([
    ".next/**",
    "node_modules/**",
    // Generated by the `workflow` package's Next.js plugin on every build;
    // already excluded from git via its own nested .gitignore (`*`).
    "src/app/.well-known/workflow/**",
  ]),
]);
